formes_cereales = {7: {'description': 'Small, crunchy spheres perfect for adding texture.',
     'nom': 'boule',
     'nom_anglais': 'ball',
     'prix': 0.08},
 8: {'description': 'Thin, flat, delicate pieces resembling leaves.',
     'nom': 'flocon',
     'nom_anglais': 'flake',
     'prix': 0.06},
 9: {'description': 'Compact, square pieces, adding a geometric, crunchy look.',
     'nom': 'cube',
     'nom_anglais': 'cube',
     'prix': 0.1},
 10: {'description': 'Curved, delicate shapes resembling soft, light petals.',
      'nom': 'pétale',
      'nom_anglais': 'petal',
      'prix': 0.22},
 20: {'description': 'Circular shapes with a hole in the center, ideal for floating in milk.',
      'nom': 'anneau',
      'nom_anglais': 'ring',
      'prix': 0.15},
 21: {'description': 'Star-shaped pieces, fun and appealing to children.',
      'nom': 'étoile',
      'nom_anglais': 'star',
      'prix': 0.22},
 29: {'description': 'Long, thin shapes resembling crunchy wood pieces.',
      'nom': 'bâtonnet',
      'nom_anglais': 'stick',
      'prix': 0.12},
 30: {'description': 'Light, airy grains that fill the space with volume.',
      'nom': 'grain soufflé',
      'nom_anglais': 'puffed grain',
      'prix': 0.18},
 31: {'description': 'Small, irregular pieces offering a dense, crunchy texture.',
      'nom': 'pépite',
      'nom_anglais': 'nugget',
      'prix': 0.2},
 48: {'description': 'A small, crisp, cross-shaped cereal piece.', 'nom': 'croix', 'nom_anglais': 'cross', 'prix': 0.2},
 49: {'description': 'Small, golden, cartoonish explorer-shaped cereal pieces.',
      'nom': 'dora',
      'nom_anglais': 'Dora',
      'prix': 0.2},
 50: {'description': 'Small, round, puffed pieces, lightly golden brown.',
      'nom': 'jouer',
      'nom_anglais': 'to play',
      'prix': 0.2},
 51: {'description': 'Small, cube-shaped bleach cereal, bright white and slightly shiny.',
      'nom': 'javel',
      'nom_anglais': 'Bleach',
      'prix': 0.2},
 52: {'description': 'Small, oval-shaped, slightly porous cereal pieces.',
      'nom': 'oeuf',
      'nom_anglais': 'egg',
      'prix': 0.2},
 55: {'description': 'Small, crispy fish-shaped cereal pieces, golden brown and slightly sweet.',
      'nom': 'poisson',
      'nom_anglais': 'fish',
      'prix': 0.2},
 58: {'description': 'Thin, crisp, green flakes resembling small, flat leaves.',
      'nom': 'feuille',
      'nom_anglais': 'leaf',
      'prix': 0.2},
 60: {'description': 'Small, twisted, crunchy cereal pieces shaped like pretzels.',
      'nom': 'bretzel',
      'nom_anglais': 'pretzel',
      'prix': 0.2},
 61: {'description': 'Small, crunchy, bottle-shaped cereal pieces with a slightly curved neck.',
      'nom': 'bouteille',
      'nom_anglais': 'bottle',
      'prix': 0.2}}

gouts_cereales = {22: {'description': 'Rich cocoa flavor with dark brown shades resembling dark chocolate.',
      'nom': 'chocolat',
      'nom_anglais': 'chocolate (brown in color)',
      'prix': 0.06},
 23: {'description': 'Simple, pure flavor with light beige or golden tones, highlighting authenticity.',
      'nom': 'nature',
      'nom_anglais': 'plain (beige in color)',
      'prix': 0.06},
 24: {'description': 'Subtle sweetness with white or golden highlights resembling sugar crystals.',
      'nom': 'sucrée',
      'nom_anglais': 'sweet (white or golden in color)',
      'prix': 0.08},
 25: {'description': 'Natural sweetness with a golden, shiny color resembling nectar.',
      'nom': 'miel',
      'nom_anglais': 'honey (yellow in color)',
      'prix': 0.12},
 26: {'description': 'Sweet, buttery flavor with an amber or golden brown color resembling melted caramel.',
      'nom': 'caramel',
      'nom_anglais': 'caramel (amber in color)',
      'prix': 0.14},
 27: {'description': 'Sweet, spiced flavor with orange-brown hues, like speculoos cookies.',
      'nom': 'spéculoos',
      'nom_anglais': 'speculoos (orange-brown in color)',
      'prix': 0.22},
 28: {'description': 'Lively, fruity flavor with shades of red and pink like strawberries and raspberries.',
      'nom': 'fruits rouges',
      'nom_anglais': 'red fruits (red in color)',
      'prix': 0.13},
 32: {'description': 'Soft, creamy flavor with a beige or ivory hue resembling vanilla pods.',
      'nom': 'vanille',
      'nom_anglais': 'vanilla (beige in color)',
      'prix': 0.1},
 33: {'description': 'Spicy, warm flavor with brown and orange hues reminiscent of cinnamon bark.',
      'nom': 'cannelle',
      'nom_anglais': 'cinnamon (brown-orange in color)',
      'prix': 0.17},
 34: {'description': 'Rich, earthy flavor with light brown or golden shades resembling roasted hazelnuts.',
      'nom': 'noisette',
      'nom_anglais': 'hazelnut (light brown in color)',
      'prix': 0.22},
 45: {'description': 'Small, creamy white pieces, possibly speckled with cocoa',
      'nom': 'chocolat blanc',
      'nom_anglais': 'chocolat blanc',
      'prix': 0.2},
 47: {'description': 'Sweet yellow cereal pieces, possibly with flecks of brown or dark yellow.',
      'nom': 'banane',
      'nom_anglais': 'banane',
      'prix': 0.2},
 54: {'description': 'Orange flakes, possibly with small bits of fish, creamy texture.',
      'nom': 'saumon',
      'nom_anglais': 'saumon',
      'prix': 0.2},
 56: {'description': 'Dark brown, possibly with small pieces of cocoa beans.',
      'nom': 'chocolat noir',
      'nom_anglais': 'chocolat noir',
      'prix': 0.2},
 57: {'description': 'Crispy, sweet, red pieces with a sugary coating',
      'nom': 'pomme',
      'nom_anglais': 'pomme',
      'prix': 0.2},
 59: {'description': 'Fermented cabbage, pale green-yellow, shredded, slightly sour.',
      'nom': 'choucroute',
      'nom_anglais': 'choucroute',
      'prix': 0.2},
 64: {'description': 'Crispy, round, segmented pieces, bright orange hue.',
      'nom': 'orange',
      'nom_anglais': 'orange',
      'prix': 0.2},
 66: {'description': 'Small, round grains of semolina, pale yellow and slightly grainy.',
      'nom': 'couscous',
      'nom_anglais': 'couscous',
      'prix': 0.2}}

categorie_cereales = {
    10: {"nom": "bio", "prix": 0.70, "description": "Natural, earthy look with green and brown tones, evoking leaves or wheat."},
    5: {"nom": "sport", "prix": 0.60, "description": "Dynamic, modern style with vibrant colors like blue or red, symbolizing energy."},
    4: {"nom": "gourmand", "prix": 0.54, "description": "Rich, appetizing design with warm, inviting tones, perfect for indulgence."}
}

test
